services:
  # ============================
  # MongoDB Database Service
  # ============================
  mongo:
    image: mongo:7
    container_name: jewelry-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - jewelry-net

  # ============================
  # Next.js Web Application
  # ============================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: zuhanaveed/jewelry-store:latest
    container_name: jewelry-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/jewelry-store
      - JWT_SECRET=mySuperSecretKey123!@#
      - ADMIN_EMAIL=admin@jewelry.com
      - ADMIN_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - jewelry-net

# ============================
# Persistent Volume for MongoDB
# ============================
volumes:
  mongo-data:
    driver: local

# ============================
# Custom Network
# ============================
networks:
  jewelry-net:
    driver: bridge
