apiVersion: v1
kind: Secret
metadata:
  name: jewelry-app-secret
  namespace: default
type: Opaque
stringData:
  MONGO_URI: mongodb://mongo-service:27017/jewelry-store
  JWT_SECRET: your-jwt-secret-key-change-this
  ADMIN_EMAIL: admin@jewelry.com
  ADMIN_PASSWORD: admin123
